### PR TITLE
docs(identity): ADR-008 On-ledger resources [DEV-1453]

### PR DESCRIPTION
**Pull request by Toktar**

### CODE REVIEW

**Review by askolesov — COMMENTED** [review]
Finally, we've got it!

**Comment by Toktar** [comment]
@Tweeddalex @askolesov Could you please review the PR?

**Comment by tweeddalex** [comment]
What I would love to see as one of your examples is a 'WriteRequest' which includes a DID Document and also its linked resource in the same transaction, for example:
[Schema DID Doc linked with Resources.txt](https://github.com/cheqd/node-docs/files/8876889/Schema.DID.Doc.linked.with.Resources.txt)

I believe this is important and should be the trigger for 'resources' being included in the DID Doc metadata
:

**Comment by askolesov** [comment]
@Tweeddalex This is not how I would do it. There are two reasons:
* It would be not easy to implement considering our current architecture where Resource module depends on DID module (which is right)
* Cosmos allow putting several messages into a single transaction, meaning you can put a CreadteDIDMsg, following as many CreateResourceMsgs as you want. ← If this behaviour is really needed, this is the way I would do it

**Comment by tweeddalex** [comment]
Quick question on the JSON for the Resources and Collections @Toktar 

In the next and previous id fields within the metadata, should the response:

`null`

have quotation marks around it? Since currently it does not. (Probably me not fully understanding JSON notation)

Should it be:

`"null"`

**Comment by Toktar** [comment]
> Quick question on the JSON for the Resources and Collections @Toktar
> 
> In the next and previous id fields within the metadata, should the response:
> 
> `null`
> 
> have quotation marks around it? Since currently it does not. (Probably me not fully understanding JSON notation)
> 
> Should it be:
> 
> `"null"`

@Tweeddalex  `null` is a valid JSON type. https://www.w3schools.com/js/js_json_datatypes.asp
So, `null` shouldn't be quoted

**Review by tweeddalex — DISMISSED** [review]

**Review by tweeddalex — DISMISSED** [review]

**Comment by rosspower11** [comment]
@Tweeddalex  - fixed the linting and most of the link issues. Overall the ones left are all Cosmos related. I think the cosmos / tendermint docs must be doing a load of changes as their docs are broken all over the site. So I think it's best we just merge in now and await some fixes to their docs as its difficult to track down the links we need. Alternative we remove all cosmos / tendermint docs

**Review by tweeddalex — APPROVED** [review]

**Pull request merged**
