### PR TITLE
docs: DEV-1967 Update node setup documentation to reflect changes implemented on cheqd-node in v1.0.x release 

### PR DESCRIPTION
**Pull request by abdulla-ashurov**
DEV-1967 Update node setup documentation to reflect changes implemented on cheqd-node in v1.0.x release:

- Updated `verificationMethod` type fields in `DIDDoc`:
    - removed `publicKeyJWK` field
    - removed `publicKeyMultibase` field 
    - renamed `type` to `verificationMethodType` field
    - added `verificationMaterial` field

- Updated `Metadata` type fields in `DidDocWithMetadata`:
    - removed `Resources` type
    - added `previousVersionId`
    - added `nextVersionId`
   
 - Updated `Service` type fields in `DIDDoc`:
    - removed `type` to `serviceType` field

- Proto files are updated:
    - renamed `CreateDID` to `CreateDIDDoc` type
    - renamed `UpdateDID` to `UpdateDIDDoc` type
    - renamed `DeactivateDID` to `DeactivateDIDDoc` type
    - renamed `GetDID` to `GetDIDDoc` type
    - renamed `QueryGetResourceRequest` to `QueryResourceRequest` type
    - renamed `QueryGetResourceResponse` to `QueryResourceResponse` type
    - renamed `QueryGetCollectionResourcesRequest` to `QueryCollectionResourcesRequest` type
    - renamed `QueryGetCollectionResourcesResponse` to `QueryCollectionResourcesResponse` type
    - updated `MsgCreateResourcePayload`: added `versionId` and `alsoKnownAs` fields
    - updated `MsgCreateResourceResponse`: removed `Resource` type and added `Metadata` type
    - removed `AllResourceVersions` type
    - removed `Resource` type
    - added `ResourceMetadata` type
    - added `ResourceWithMetadata` type
    - added `QueryResourceMetadataRequest` type
    - added `QueryResourceMetadataResponse` type

    
- Updated [Overview of Resource and Resource collection](https://github.com/abdulla-ashurov/node-docs/blob/DEV-1967-update-node-docs/.gitbook/assets/adr008-resource-flow-simplified.png) diagram
- Updated [Overview of Resource and Resource flow detailed](https://github.com/abdulla-ashurov/node-docs/blob/main/.gitbook/assets/adr008-resource-flow-detailed.png) diagram

### CODE REVIEW

**Comment by ankurdotb** [comment]
Task linked: [DEV-1967 Update node setup documentation to reflect changes implemented on cheqd-node in v1.0.x release](https://app.clickup.com/t/6600954/DEV-1967)

**Review by tweeddalex — COMMENTED** [review]
Hey @abdulla-ashurov a few things here:

1. Why has linkedResources been removed from DIDDocumentMetadata? I believe that linkedResources should be shown here.

2. In the service section, keep "type" as it is, rather than "serviceType" since this needs to follow DID Core. 

3. Whenever a key is used in a DIDDoc, for example in 'capabilityDelegation', it should usually reference a key in the 'verificationMethod' section. You are allowed to embed new keys for specific verificationMethod Relationships, however, you need to include all the key material in the specific section.

**Review by tweeddalex — COMMENTED** [review]
I am also confused about why we have added a section called "verification_material" - this is not part of the DID Core spec. 

One final point is that there is a mix of camel case and snake case here, can we please keep it consistent throughout - @ankurdotb I assume we just want this all to be in camelCase

**Comment by abdulla-ashurov** [comment]
> Hey @abdulla-ashurov a few things here:
> 
> 1. Why has linkedResources been removed from DIDDocumentMetadata? I believe that linkedResources should be shown here.
> 2. In the service section, keep "type" as it is, rather than "serviceType" since this needs to follow DID Core.
> 3. Whenever a key is used in a DIDDoc, for example in 'capabilityDelegation', it should usually reference a key in the 'verificationMethod' section. You are allowed to embed new keys for specific verificationMethod Relationships, however, you need to include all the key material in the specific section.

Hey @Tweeddalex!
1. Currently, `DIDDoc Metadata` looks like that - https://github.com/cheqd/cheqd-node/blob/5543e7e72a381373b349932af2622e4dd735f0d7/proto/cheqd/did/v2/diddoc.proto#L93, where we removed `LinkedResource` type from `Metadata` type - https://github.com/cheqd/cheqd-node/blob/5543e7e72a381373b349932af2622e4dd735f0d7/proto/cheqd/did/v2/diddoc.proto#L103.

**Comment by lampkin-diet** [comment]
> Hey @abdulla-ashurov a few things here:
> 
> 1. Why has linkedResources been removed from DIDDocumentMetadata? I believe that linkedResources should be shown here.
> 2. In the service section, keep "type" as it is, rather than "serviceType" since this needs to follow DID Core.
> 3. Whenever a key is used in a DIDDoc, for example in 'capabilityDelegation', it should usually reference a key in the 'verificationMethod' section. You are allowed to embed new keys for specific verificationMethod Relationships, however, you need to include all the key material in the specific section.

Hey @Tweeddalex . About your comments:
- in DIDDocumentMetadata on the ledger side we don't have the field `linkedResources`. Maybe we need to add this for resolver side if we respond with it there?
- ledger respond with `serviceType` for now. Resolver does this transformation and respond with did-core spec.

**Comment by lampkin-diet** [comment]
@Tweeddalex Also, the same situation with mix camelCase and snake case. For now, payloads for ledger only keep camelCase, cause we have not set up specific handler for proto which will allow us to accept camelCased and snake cased values. Respond from the ledger is in format of snake case. In general, the main function of formatting output as in did-core spec is on the resolver side.

**Comment by tweeddalex** [comment]
Ah okay that makes a lot of sense about the resolver handling the conversions. That's what I thought, just wanted to confirm. 

I still think my point around verification methods is valid. See https://www.w3.org/TR/did-core/#dfn-assertionmethod regarding how keys that are not referenced from the verificationMethod section should be handled.

**Comment by tweeddalex** [comment]
@abdulla-ashurov is there more work needed on this with the latest changes to the 1.x release?

**Comment by abdulla-ashurov** [comment]
> @abdulla-ashurov is there more work needed on this with the latest changes to the 1.x release?

I took a look - needed some changes

**Pull request closed without merging**
